name = "nayabharatyojana"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
vars = { ENVIRONMENT = "production" }

# Configure routes for Next.js
[[routes]]
pattern = "/_next/*"
content_type = "application/javascript"

[[routes]]
pattern = "/api/*"
script = "api" 