[build]
command = "npm run build"
pages_build_output_dir = ".next/standalone"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"

[site]
bucket = ".next/standalone"

[env.production]
routes = [
  { pattern = "/*", zone_name = "nayabharatyojana.in" }
] 