CREATE TABLE IF NOT EXISTS public.prompt_usage (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(256) NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 