import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";
import { db } from '@/lib/firebase-admin';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function POST(request: Request) {
  try {
    const { text } = await request.json();

    // Initialize the model
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });

    // Generate humanized text
    const result = await model.generateContent(`You will be given a piece of text that sounds like it was generated by AI. Your task is to rewrite this text to make it sound more human-written.

Guidelines for rewriting:
1. Use a conversational tone and natural language
2. Keep the original meaning intact
3. Make it more engaging and readable
4. Add natural flow and transitions
5. Use varied sentence structures
6. Maintain appropriate formality level

Original text to humanize:
"${text}"

Return only the humanized text without any explanations or additional formatting.`);

    const response = await result.response;
    const humanizedText = response.text();

    // Store in Firestore
    await db.collection('humanized_texts').add({
      originalText: text,
      humanizedText,
      createdAt: new Date(),
    });

    return NextResponse.json({ humanizedText });
  } catch (error) {
    console.error('Error:', error);
    return NextResponse.json({ error: 'Failed to humanize text' }, { status: 500 });
  }
} 